---

provisioner:
  name: chef_zero

platforms:
  - name: centos-6

verifier:
  name: inspec
  pty: true
  # sudo_command: 'ssh -t'

suites:
  - name: auto-master
    run_list:
      - recipe[auto_master::default]
  - name: map-entry
    run_list:
      - recipe[map_entry::default]
  - name: multi
    run_list:
      - recipe[multi::default]
  - name: nfs
    run_list:
      - recipe[nfs::default]
