---
provisioner:
  name: chef_zero

platforms:
  - name: centos-6

verifier:
  name: inspec
  pty: true

suites:
  - name: auto-master
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[auto_master_test::default]
  - name: map-entry
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[map_entry_test::default]
  - name: multi
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[multi_test::default]
  - name: nfs
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[nfs_test::default]
