---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

verifier:
  name: inspec

suites:
  - name: auto-master
    run_list:
      - recipe[auto_master_test::default]
  - name: map-entry
    run_list:
      - recipe[map_entry_test::default]
  - name: multi
    run_list:
      - recipe[multi_test::default]
  - name: nfs
    run_list:
      - recipe[nfs_test::default]
